/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import File.Arquivos;
import javax.swing.JOptionPane;

/**
 *
 * @author Danilo Abreu
 */
public class InicialGUI extends javax.swing.JFrame {

    /**
     * Creates new form InicialGUI
     */
    Arquivos arqf;
    public InicialGUI() {
        initComponents();
        arqf = new Arquivos("cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        novoBT = new javax.swing.JButton();
        exibirBT = new javax.swing.JButton();
        editarBT = new javax.swing.JButton();
        removerBT = new javax.swing.JButton();
        logofBT = new javax.swing.JButton();
        sairBT = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        setExtendedState(6);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        novoBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-contact-new-icon.png"))); // NOI18N
        novoBT.setToolTipText("Cadastrar Novo");
        novoBT.setFocusable(false);
        novoBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        novoBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        novoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoBTActionPerformed(evt);
            }
        });
        jToolBar1.add(novoBT);

        exibirBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-view-list-details-icon.png"))); // NOI18N
        exibirBT.setToolTipText("Listar");
        exibirBT.setFocusable(false);
        exibirBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exibirBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(exibirBT);

        editarBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Male-user-edit-icon.png"))); // NOI18N
        editarBT.setToolTipText("Editar");
        editarBT.setFocusable(false);
        editarBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(editarBT);

        removerBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Male-user-remove-icon.png"))); // NOI18N
        removerBT.setToolTipText("Remover Usuário");
        removerBT.setFocusable(false);
        removerBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removerBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(removerBT);

        logofBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout-icon.png"))); // NOI18N
        logofBT.setToolTipText("Fazer Logout");
        logofBT.setFocusable(false);
        logofBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logofBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logofBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logofBTActionPerformed(evt);
            }
        });
        jToolBar1.add(logofBT);

        sairBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Windows-Close-Program-iconBig.png"))); // NOI18N
        sairBT.setToolTipText("Fechar o Programa");
        sairBT.setFocusable(false);
        sairBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sairBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sairBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBTActionPerformed(evt);
            }
        });
        jToolBar1.add(sairBT);

        jMenu1.setText("Arquivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-edit-add-icon.png"))); // NOI18N
        jMenuItem1.setText("Novo Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout-iconSmall.png"))); // NOI18N
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Administrar");

        jMenuItem3.setText("Usuários");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Exibir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void novoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoBTActionPerformed
        // TODO add your handling code here:
        ClienteGUI.getInstance().setVisible(true);
    }//GEN-LAST:event_novoBTActionPerformed
    public void sair(){
       int op = JOptionPane.showConfirmDialog(null, "Deseja Sair", "Sair do Sistema", JOptionPane.YES_NO_OPTION);
        if(op == JOptionPane.YES_OPTION){
            dispose();
            new LoginGUI(this,true).setVisible(true);
        }
    }
    private void logofBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logofBTActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_logofBTActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //ClienteJanela.getInstance().setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        UsuarioGUI.getInstance().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void sairBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBTActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Fechando...");
        System.exit(0);
    }//GEN-LAST:event_sairBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicialGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarBT;
    private javax.swing.JButton exibirBT;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton logofBT;
    private javax.swing.JButton novoBT;
    private javax.swing.JButton removerBT;
    private javax.swing.JButton sairBT;
    // End of variables declaration//GEN-END:variables
}
